# docker-compose.yml
version: '3.8'

services:
  # The SentryFlow Risk Engine
  sentryflow-api:
    build: .
    container_name: sentryflow_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - sentryflow-network
  # Redis for <30ms Caching & Frequency Counters
  redis:
    image: redis:7.2-alpine
    container_name: sentryflow_redis
    ports:
      - "6379:6379"
    networks:
      - sentryflow-network
  # The Monitoring Dashboard
  sentryflow-dashboard:
    build: .
    command: streamlit run research/monitoring_dashboard.py --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app

networks:
  sentryflow-network:
    driver: bridge